spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    hikari:
      validation-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true
        dialect: org.hibernate.dialect.MySQLDialect